name: Docker Image CI

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/apoorva64/headscale-tailscale-connector:latest

      - name: Push the Docker image
        run: docker push ghcr.io/apoorva64/headscale-tailscale-connector:latest
